<a href="https://colab.research.google.com/github/Navneet170904/ANN/blob/main/workshop_day2_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part1- Data Processing

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

Importing the dataset

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/Churn_Modelling.csv")
x  = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

Spliting the dataset into the Training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

Part2 - Building the ANN

Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [ ]:
#ann.add(tf.keras.Input(shape=(11,)))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

Part3 - Training the ANN

compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training set

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
250/250 [==============================] - 1s 3ms/step - loss: 2.8536 - accuracy: 0.6342
Epoch 2/20
250/250 [==============================] - 1s 3ms/step - loss: 2.0336 - accuracy: 0.7174
Epoch 3/20
250/250 [==============================] - 1s 2ms/step - loss: 1.3207 - accuracy: 0.7315
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.6470 - accuracy: 0.7511
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7671
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.5036 - accuracy: 0.7828
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4878 - accuracy: 0.7908
Epoch 8/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4777 - accuracy: 0.7944
Epoch 9/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4715 - accuracy: 0.7943
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4668 - accuracy: 0.7960

Part4 - Making prediction and evaluation the

Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 83ms/step
[[False]]


In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1559   36]
 [ 343   62]]


0.8105